### ISSUE TITLE
Exercise: Alter Table

### ISSUE THREAD

**Issue by ayodeleopetumo** [ayodeleDD/MySQL#1]
Create a table named "testing_table" with following fields: name (string)contact_name (string)roll_no (string) Now:Delete column name, rename contact_name to username. Add two fields first_name, last_name. Also change the type of roll_no to integer.

https://github.com/ayodeleDD/MySQL/blob/master/alter-table.sql

**Comment by segunadeleye** [comment]
Looks good. However, `CREATE TABLE` query requires a semi colon. Please update
